apiVersion: 1

deleteDatasources:
  - name: PostgreSQL-MLOps
    orgId: 1

datasources:
  - name: PostgreSQL-MLOps
    uid: PostgreSQL-MLOps
    type: postgres
    access: proxy
    url: postgres:5432
    database: airflow
    user: airflow
    secureJsonData:
      password: "airflow"
    jsonData:
      sslmode: "disable"
      postgresVersion: 16
    isDefault: true
    editable: true
